### ISSUE TITLE
What competitions should we enter as a team?

### ISSUE THREAD

**Issue by patrickwalls** [ubcs3/2017-Fall#1]
There are many [Kaggle competitions](https://www.kaggle.com/competitions) currently open. Let's pick a few to enter as a group. Make your suggestions here!

**Comment by ShunChi100** [comment]
Thank you for organizing this. Does the competition have to be ongoing one?

**Comment by topspinj** [comment]
These look interesting:
- [NYC Taxi Trip Duration](https://www.kaggle.com/c/nyc-taxi-trip-duration) - expired
- [Zillow Home Value Prediction](https://www.kaggle.com/c/zillow-prize-1) - active competition
- [Web Traffic Time Series Forecasting of Wikipedia Pages](https://www.kaggle.com/c/web-traffic-time-series-forecasting) - also active

**Comment by peter0083** [comment]
Zillow Home Value Prediction +1

**Comment by ShunChi100** [comment]
Zillow Home Value Prediction is going to close for the first round and only the first 100 teams can compete for the second round. But it is a good one for practicing classical ML algorithms.

**Comment by patrickwalls** [comment]
@ShunChi100 We can do any competition since we're just learning.
