### ISSUE TITLE
"kernel appears to have died" taxi cab on syzygy

### ISSUE THREAD

**Issue by cbm755** [ubcs3/2017-Fall#4]
Does anyone else get this?  Perhaps some memory limitation... does it effect others?  If so we can ask @ianabc to look into it.

**Comment by ianabc** [comment]
It is a memory limitation inside the container.
```
Nov 04 23:13:08 ubc.syzygy.ca kernel: python3 invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=0
```
We've put a 1GB limit on the containers and any child processes (including kernels) get included in that. The limit is mainly for us to support larger numbers of simultaneous users, but we can revisit it again later on.

**Comment by cbm755** [comment]
That makes sense.

It would be nice if jupyter (and hence syzygy) gave an indication of that.  But if (the kernel named) Linux's OOM killer kicks in, jupyter cannot tell the difference between this and (for example) a segfault.  We also have no guarantee that OOM killer kills python.  Could take out some other random process (hence corrupting my .ipynb file for example).

Scary stuff.  Does Syzygy have an issue tracker?  It would certainly be nice to have a better low memory story than this...

**Comment by ianabc** [comment]
We can probably influence the process chosen by playing with `oom_score_adj`. I'll look into it.
